/*SELECT SUM(VALORE_DONAZIONE) AS Donazione 
FROM DONARE
WHERE ID_PROGETTO = 'Il tuo progetto'

SELECT P.NOME_PROGETTO AS Progetto
FROM DONARE D
INNER JOIN PROGETTI P ON D.ID_PROGETTO = P.ID_PROGETTO
WHERE D.ID_ACCOUNT = 'account_preciso'
GROUP BY P.NOME_PROGETTO*/



